"""
Markdown to HTML converter.

Converts markdown blog posts to styled HTML with:
- Syntax highlighting for code
- Mermaid diagram rendering
- Responsive design
- Embedded images
"""

from pathlib import Path
from typing import Optional
import markdown
from markdown.extensions import fenced_code, tables, toc, codehilite
from bs4 import BeautifulSoup

from src.utils.logger import setup_logger


logger = setup_logger(__name__)


class MarkdownToHTMLConverter:
    """Converter from markdown to styled HTML."""
    
    def __init__(self) -> None:
        """Initialize the converter."""
        self.md = markdown.Markdown(
            extensions=[
                'fenced_code',
                'tables',
                'toc',
                'codehilite',
                'nl2br',
                'sane_lists',
            ],
            extension_configs={
                'codehilite': {
                    'css_class': 'highlight',
                    'linenums': False,
                },
            },
        )
        logger.info("MarkdownToHTMLConverter initialized")
    
    def convert(
        self,
        markdown_content: str,
        title: str,
        meta_description: str,
        image_path: Optional[Path] = None,
    ) -> str:
        """
        Convert markdown to full HTML page.
        
        Args:
            markdown_content: Blog content in markdown
            title: Page title
            meta_description: SEO meta description
            image_path: Optional header image path
            
        Returns:
            Complete HTML document
        """
        logger.info("Converting markdown to HTML")
        
        # Convert markdown to HTML
        body_html = self.md.convert(markdown_content)
        
        # Wrap in full HTML document
        html = self._create_html_document(
            body_html,
            title,
            meta_description,
            image_path,
        )
        
        # Process Mermaid diagrams
        html = self._process_mermaid(html)
        
        logger.info("Conversion complete")
        return html
    
    def _create_html_document(
        self,
        body_html: str,
        title: str,
        meta_description: str,
        image_path: Optional[Path],
    ) -> str:
        """Create complete HTML document with styling."""
        
        image_tag = ""
        if image_path:
            image_tag = f'<img src="{image_path}" alt="{title}" class="header-image">'
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{meta_description}">
    <title>{title}</title>
    
    <!-- Mermaid JS for diagrams -->
    <script type="module">
        import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
        mermaid.initialize({{ startOnLoad: true }});
    </script>
    
    <!-- Syntax Highlighting -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css">
    
    <style>
        {self._get_css()}
    </style>
</head>
<body>
    <article class="blog-post">
        {image_tag}
        <header>
            <h1>{title}</h1>
        </header>
        <main>
            {body_html}
        </main>
        <footer>
            <p>Generated by Blog Data Analyst AI Agent</p>
        </footer>
    </article>
</body>
</html>"""
        
        return html
    
    @staticmethod
    def _get_css() -> str:
        """Get CSS styles for the HTML document."""
        return """
        :root {
            --primary-color: #2563eb;
            --text-color: #1f2937;
            --bg-color: #ffffff;
            --code-bg: #f3f4f6;
            --border-color: #e5e7eb;
        }
        
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.7;
            color: var(--text-color);
            background-color: var(--bg-color);
            padding: 2rem;
        }
        
        .blog-post {
            max-width: 800px;
            margin: 0 auto;
            background: white;
            padding: 3rem;
            border-radius: 8px;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
        }
        
        .header-image {
            width: 100%;
            height: auto;
            border-radius: 8px;
            margin-bottom: 2rem;
        }
        
        h1, h2, h3, h4, h5, h6 {
            margin-top: 2rem;
            margin-bottom: 1rem;
            font-weight: 600;
            line-height: 1.3;
        }
        
        h1 {
            font-size: 2.5rem;
            color: var(--primary-color);
            margin-top: 0;
        }
        
        h2 {
            font-size: 2rem;
            padding-bottom: 0.5rem;
            border-bottom: 2px solid var(--border-color);
        }
        
        h3 {
            font-size: 1.5rem;
        }
        
        p {
            margin-bottom: 1.5rem;
        }
        
        a {
            color: var(--primary-color);
            text-decoration: none;
        }
        
        a:hover {
            text-decoration: underline;
        }
        
        code {
            background: var(--code-bg);
            padding: 0.2rem 0.4rem;
            border-radius: 3px;
            font-family: 'Monaco', 'Courier New', monospace;
            font-size: 0.9em;
        }
        
        pre {
            background: #1f2937;
            color: #f3f4f6;
            padding: 1.5rem;
            border-radius: 8px;
            overflow-x: auto;
            margin: 1.5rem 0;
        }
        
        pre code {
            background: none;
            padding: 0;
            color: inherit;
        }
        
        ul, ol {
            margin-left: 2rem;
            margin-bottom: 1.5rem;
        }
        
        li {
            margin-bottom: 0.5rem;
        }
        
        blockquote {
            border-left: 4px solid var(--primary-color);
            padding-left: 1.5rem;
            margin: 1.5rem 0;
            font-style: italic;
            color: #6b7280;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 1.5rem 0;
        }
        
        th, td {
            padding: 0.75rem;
            border: 1px solid var(--border-color);
            text-align: left;
        }
        
        th {
            background: var(--code-bg);
            font-weight: 600;
        }
        
        footer {
            margin-top: 3rem;
            padding-top: 2rem;
            border-top: 1px solid var(--border-color);
            text-align: center;
            color: #9ca3af;
            font-size: 0.9rem;
        }
        
        @media (max-width: 768px) {
            body {
                padding: 1rem;
            }
            
            .blog-post {
                padding: 1.5rem;
            }
            
            h1 {
                font-size: 2rem;
            }
            
            h2 {
                font-size: 1.5rem;
            }
        }
        """
    
    @staticmethod
    def _process_mermaid(html: str) -> str:
        """Process Mermaid diagram code blocks."""
        soup = BeautifulSoup(html, 'html.parser')
        
        # Find code blocks with 'mermaid' language
        for code_block in soup.find_all('code'):
            if 'mermaid' in code_block.get('class', []):
                # Convert code block to mermaid div
                mermaid_div = soup.new_tag('div', **{'class': 'mermaid'})
                mermaid_div.string = code_block.get_text()
                
                # Replace pre > code with just the div
                parent = code_block.parent
                if parent and parent.name == 'pre':
                    parent.replace_with(mermaid_div)
        
        return str(soup)
